_target_: src.models.unified_ho_module.UnifiedHOModule
lr: 0.001
weight_decay: 0.0005

fcn:
  _target_: src.models.unified_ho_module.UnifiedFCNModule
  net: convnext_tiny
  num_cpts: 21
  obj_classes: 9
  verb_classes: 12
  batchnorm: False

temporal:
  _target_: src.models.unified_ho_module.TemporalModule
