# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: h2o.yaml
  - model: model.yaml
  - callbacks: null
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: 25

name: "default"

# passing checkpoint path is necessary
ckpt_path: ${data_dir}/logs/experiments/runs/default/2022-06-28_10-52-03/checkpoints/last.ckpt
